#!/bin/bash

rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/sound_output_menu.rasi"

# Title text
title="Default sound output"

# Options
speakers=" Speakers"
headset=" Headset"


# Variable passed to rofi
options="$speakers\n$headset"

chosen="$(echo -e "$options" | $rofi_command -p "$title" -dmenu -selected-row 0)"
case $chosen in
    $speakers)
	pactl set-card-profile usb-Logitech_G533_Gaming_Headset-00 off 
	pactl set-card-profile alsa_card.pci-0000_2f_00.4 output:analog-stereo
	;;
    $headset)
	pactl set-card-profile alsa_card.pci-0000_2f_00.4 off 
	pactl set-card-profile usb-Logitech_G533_Gaming_Headset-00 output:analog-stereo
        ;;
esac

